apiVersion: v1
kind: Service
metadata:
  name: {{ include "mm-pg-chart.fullname" . }}
  labels:
    {{- include "mm-pg-chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mm-pg-chart.selectorLabels" . | nindent 4 }}
