-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000000-create-table-account
CREATE TABLE account (
  id bigint,
  name varchar(255),
  theme varchar(10),
  currency varchar(3),
  user_id varchar(255)
);

-- changeset "Gasymov Ruslan":000000-create-constraint-account
ALTER TABLE account ALTER COLUMN id SET NOT NULL;
ALTER TABLE account ADD PRIMARY KEY (id);
ALTER TABLE account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE account
  ADD CONSTRAINT fk_account_user
  FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE users
  ADD CONSTRAINT fk_users_current_account
  FOREIGN KEY (current_account_id) REFERENCES account(id);
