-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000000-create-table-expense_category
CREATE TABLE expense_category (
  id bigint,
  account_id bigint,
  name varchar(255)
);

-- changeset "Gasymov Ruslan":000000-create-constraint-expense_category
ALTER TABLE expense_category ALTER COLUMN id SET NOT NULL;
ALTER TABLE expense_category ADD PRIMARY KEY (id);
ALTER TABLE expense_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE expense_category
  ADD CONSTRAINT fk_expense_category_account
  FOREIGN KEY (account_id) REFERENCES account(id);
ALTER TABLE expense_category
  ADD CONSTRAINT expense_category_name_unique UNIQUE (name, account_id);

-- changeset "Gasymov Ruslan":000001-create-constraint-expense_category
ALTER TABLE expense_category ALTER COLUMN name SET NOT NULL;

-- changeset "Gasymov Ruslan":000002-create-constraint-expense_category
ALTER TABLE expense_category ALTER COLUMN account_id SET NOT NULL;
