-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000000-create-table-expense
CREATE TABLE expense (
  id bigint,
  account_id bigint,
  category_id bigint,
  saving_id bigint,
  date date,
  description varchar(255),
  value_ numeric(102, 2),
  is_planned boolean
);

-- changeset "Gasymov Ruslan":000000-create-constraint-expense
ALTER TABLE expense ALTER COLUMN id SET NOT NULL;
ALTER TABLE expense ALTER COLUMN date SET NOT NULL;
ALTER TABLE expense ALTER COLUMN value_ SET NOT NULL;
ALTER TABLE expense ADD PRIMARY KEY (id);
ALTER TABLE expense ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE expense
  ADD CONSTRAINT fk_expense_expense_category
  FOREIGN KEY (category_id) REFERENCES expense_category(id);
ALTER TABLE expense
  ADD CONSTRAINT fk_expense_saving
  FOREIGN KEY (saving_id) REFERENCES saving(id);
ALTER TABLE expense
  ADD CONSTRAINT fk_expense_account
  FOREIGN KEY (account_id) REFERENCES account(id);

-- changeset "Gasymov Ruslan":000001-create-constraint-expense
ALTER TABLE expense ALTER COLUMN account_id SET NOT NULL;
ALTER TABLE expense ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE expense ALTER COLUMN saving_id SET NOT NULL;
