-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000000-create-table-history
CREATE TABLE history (
  id bigint,
  action_type varchar(255),
  operation_type varchar(255),
  account_id bigint,
  old_operation text,
  new_operation text,
  modified_at timestamp DEFAULT now()
);

-- changeset "Gasymov Ruslan":000000-create-constraint-history
ALTER TABLE history ALTER COLUMN id SET NOT NULL;
ALTER TABLE history ALTER COLUMN action_type SET NOT NULL;
ALTER TABLE history ALTER COLUMN operation_type SET NOT NULL;
ALTER TABLE history ADD PRIMARY KEY (id);
ALTER TABLE history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE history
  ADD CONSTRAINT fk_history_account
  FOREIGN KEY (account_id) REFERENCES account(id);

-- changeset "Gasymov Ruslan":000001-create-constraint-history
ALTER TABLE history ALTER COLUMN account_id SET NOT NULL;
