-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000000-create-table-income_category
CREATE TABLE income_category (
  id bigint,
  account_id bigint,
  name varchar(255)
);

-- changeset "Gasymov Ruslan":000000-create-constraint-income_category
ALTER TABLE income_category ALTER COLUMN id SET NOT NULL;
ALTER TABLE income_category ADD PRIMARY KEY (id);
ALTER TABLE income_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE income_category
  ADD CONSTRAINT fk_income_category_account
  FOREIGN KEY (account_id) REFERENCES account(id);
ALTER TABLE income_category
  ADD CONSTRAINT income_category_name_unique UNIQUE (name, account_id);

-- changeset "Gasymov Ruslan":000001-create-constraint-income_category
ALTER TABLE income_category ALTER COLUMN name SET NOT NULL;

-- changeset "Gasymov Ruslan":000002-create-constraint-income_category
ALTER TABLE income_category ALTER COLUMN account_id SET NOT NULL;
