-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000000-create-table-income
CREATE TABLE income (
  id bigint,
  account_id bigint,
  category_id bigint,
  saving_id bigint,
  date date,
  description varchar(255),
  value_ numeric(102, 2),
  is_planned boolean
);

-- changeset "Gasymov Ruslan":000000-create-constraint-income
ALTER TABLE income ALTER COLUMN id SET NOT NULL;
ALTER TABLE income ALTER COLUMN date SET NOT NULL;
ALTER TABLE income ALTER COLUMN value_ SET NOT NULL;
ALTER TABLE income ADD PRIMARY KEY (id);
ALTER TABLE income ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE income
  ADD CONSTRAINT fk_income_income_category
  FOREIGN KEY (category_id) REFERENCES income_category(id);
ALTER TABLE income
  ADD CONSTRAINT fk_income_saving
  FOREIGN KEY (saving_id) REFERENCES saving(id);
ALTER TABLE income
  ADD CONSTRAINT fk_income_account
  FOREIGN KEY (account_id) REFERENCES account(id);

-- changeset "Gasymov Ruslan":000001-create-constraint-income
ALTER TABLE income ALTER COLUMN account_id SET NOT NULL;
ALTER TABLE income ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE income ALTER COLUMN saving_id SET NOT NULL;
