-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000001-create-table-report-tasks
CREATE TABLE report_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  telegram_id bigint,
  chat_id bigint,
  start_date date,
  end_date date,
  account_id bigint,
  status varchar(50),
  retry_count int DEFAULT 0,
  max_retries int,
  error_message text,
  created_at timestamp,
  updated_at timestamp,
  next_retry_at timestamp
);

-- changeset "Gasymov Ruslan":000001-create-constraint-report-tasks
ALTER TABLE report_tasks ADD PRIMARY KEY (id);
ALTER TABLE report_tasks ALTER COLUMN telegram_id SET NOT NULL;
ALTER TABLE report_tasks ALTER COLUMN chat_id SET NOT NULL;
ALTER TABLE report_tasks ALTER COLUMN start_date SET NOT NULL;
ALTER TABLE report_tasks ALTER COLUMN end_date SET NOT NULL;
ALTER TABLE report_tasks ALTER COLUMN status SET NOT NULL;
ALTER TABLE report_tasks ALTER COLUMN max_retries SET NOT NULL;
ALTER TABLE report_tasks ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE report_tasks ALTER COLUMN account_id SET NOT NULL;

-- changeset "Gasymov Ruslan":000001-create-index-report-tasks
CREATE INDEX idx_report_tasks_status ON report_tasks(status);
CREATE INDEX idx_report_tasks_next_retry ON report_tasks(next_retry_at);

-- changeset "Gasymov Ruslan":000001-create-table-telegram-user-states
CREATE TABLE telegram_user_states (
  telegram_id bigint,
  state varchar(50),
  selected_account_id bigint,
  updated_at timestamp
);

-- changeset "Gasymov Ruslan":000001-create-constraint-telegram-user-states
ALTER TABLE telegram_user_states ADD PRIMARY KEY (telegram_id);
ALTER TABLE telegram_user_states ALTER COLUMN state SET NOT NULL;
ALTER TABLE telegram_user_states ALTER COLUMN updated_at SET NOT NULL;
