-- liquibase formatted sql

-- changeset "Gasymov Ruslan":000000-create-table-saving
CREATE TABLE saving (
  id bigint,
  account_id bigint,
  date date,
  value_ numeric(102, 2)
);

-- changeset "Gasymov Ruslan":000000-create-constraint-saving
ALTER TABLE saving ALTER COLUMN id SET NOT NULL;
ALTER TABLE saving ADD PRIMARY KEY (id);
ALTER TABLE saving ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE saving
  ADD CONSTRAINT fk_saving_account
  FOREIGN KEY (account_id) REFERENCES account(id);
ALTER TABLE saving
  ADD CONSTRAINT saving_date_unique UNIQUE (date, account_id);

-- changeset "Gasymov Ruslan":000001-create-constraint-saving
ALTER TABLE saving ALTER COLUMN account_id SET NOT NULL;
ALTER TABLE saving ALTER COLUMN date SET NOT NULL;
ALTER TABLE saving ALTER COLUMN value_ SET NOT NULL;
