apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-backend-deployment
  labels:
    app: mm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm-backend
  template:
    metadata:
      labels:
        app: mm-backend
    spec:
      containers:
      - image: money-manager-backend:1.1.0
        imagePullPolicy: IfNotPresent
        name: money-manager-backend
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mm-secrets
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mm-secrets
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: mm-secrets
              key: postgres-db
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: mm-configmap
              key: postgres-host
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(POSTGRES_HOST)/$(POSTGRES_DB)
