# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
fullnameOverride: mm-postgres

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  tag: 16.1
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5432 # Service port accessible from outside (only in k8s cluster)
  targetPort: 5432 # Container port

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env:
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: mm-secrets
        key: postgres-user
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mm-secrets
        key: postgres-password
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: mm-secrets
        key: postgres-db
