apiVersion: v1
kind: Secret
metadata:
  name: mm-secret-tls
  labels:
    {{- include "mm-config-chart.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- toYaml .Values.tlsSecrets | nindent 2 }}
