apiVersion: v1
kind: Secret
metadata:
  name: mm-yc-registry-key
  labels:
    {{- include "mm-config-chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
